### ISSUE TITLE
CSV is exporting duplicate data

### ISSUE THREAD

**Issue by sergiomario** [okfn-brasil/censo-querido-diario#19]
## The problem
When exporting data on the mapping screen, CSV is showing duplicate mappings.

Following is the query line that needs to be changed
https://github.com/okfn-brasil/censo-querido-diario/blob/f92e42e45ad2e71911a36276154333e64f32c513/formulario/views.py#L99

## Suggestion
` mapeados = Mapeamento.objects.filter(validacao=True).order_by('municipio').distinct() `

**Comment by davidpalves** [comment]
The bug also occurs when the CSV should show non-mapped cities in the export, when there are cities that are mapped. E. g.
```
Recife | <non-filled data>
---------------------------------
Recife (PE) | <filled data>
```
https://github.com/okfn-brasil/censo-querido-diario/blob/f92e42e45ad2e71911a36276154333e64f32c513/formulario/views.py#L124
