### ISSUE TITLE
Decidir uma ferramenta de colaboração para a escrita do relatório // Choose collaboration tools for writing the report

### ISSUE THREAD

**Issue by bcbernardo** [okfn-brasil/censo-querido-diario#29]
## Em português

_For english, see [below](#in-english)._

Com a etapa de coleta e validação do censo chegando ao fim, e a etapa de análise se aproximando, seria importante estabelecermos uma ferramenta de colaboração para a escrita do relatório.

Proponho usarmos o [HackMD](https://hackmd.io/ "HackMD - Editor de textos em Markdown"), que é um editor de markdown que tem as seguintes [funcionalidades](https://hackmd.io/c/tutorials/%2Fs%2Ffeatures "HackMD - Funcionalidades"):

- Possibilidade de criar sessões colaborativas;
- Comentários para colaboração assíncrona;
- Previsão da visualização final em tempo real, ao lado do editor em markdown;
- Barra de ferramentas para facilitar a edição por quem não domina markdown;
- Possibilidade de [criar "livros"](https://hackmd.io/c/tutorials/%2Fs%2Fhow-to-create-book "Tutorial de como criar um livro no HackMD") a partir de grupos de documentos;
- Integração com o GitHub para controle de versão;
- Gratuito para times públicos.

A ideia de usar um editor em markdown é facilitar a conversão para HTML (e para quase qualquer formato, com ferramentas como o [Pandoc](https://pandoc.org/ "Pandoc - Conversor Universal de Documentos")), de modo que o relatório final possa ser disponibilizado em formato acessível. Também seria possível usar uma ferramenta mais tradicional, como o [Google Docs](https://www.google.com/intl/pt-BR/docs/about/ "Google Docs"), mas é possível que isso acarrete um pouco mais de trabalho na diagramação.

O que acham? Alguém tem outra sugestão de ferramenta?

## In English

As the data collection and valitation stages of the census come to an end, and the beggining of the analysis stage gets closer, it would be important to establish a collaboration tool for writing the report.

I suggest using [HackMD](https://hackmd.io/ "HackMD markdown editor"), a markdown editor with the following [features](https://hackmd.io/c/tutorials/%2Fs%2Ffeatures "HackMD features"):

- Collaborative sessions, for synchronous collaboration
- Comments for asynchronous collaboration
- Real-time preview of the final document next to the Markdown editor;
- Toolbar for easy editing by those who don't know Markdown (WYSIWIG tools)
- Integration with GitHub for version control
- Optional [creation of "books"](https://hackmd.io/c/tutorials/%2Fs%2Fhow-to-create-book "Tutorial for creating books in HackMD") from a collection of documents
- Free for public teams.

The rationale behind using a markdown editor is to facilitate the eventual conversion to HTML (and nearly any format, using tools like [Pandoc](https://pandoc.org/ "Pandoc - Universal Document Converter")), so that the final report can be published in an accessible format. It would be possible also to use a more traditional approach, like [Google Docs](https://www.google.com/intl/pt-BR/docs/about/ "Google Docs"), but this might mean more work in the diagramation phase. 

How do you feel about that? Does anyone have another suggestion?

**Comment by sergiomario** [comment]
## Em português

Olá @bcbernardo. Obrigado pela proposta.

Eu gostei e acho que o HackMD pode ser nosso mecanismo de construção do relatório. Inclusive eu entendi a sincronização com o github e me pareceu simples.

Podemos ter uma aba no site como o [blog](https://queridodiario.ok.org.br/blog) para embarcar os relatórios e seguir na linha de conteúdo em HTML como você propôs.

## In English

Hi @bcbernardo. Thanks!

I liked it and I think that HackMD can be our report building mechanism. I even understood the synchronization with Github and it's very simple.

We can have a tab on the website like [blog](https://queridodiario.ok.org.br/blog) to upload HTML reports as you proposed.
