### ISSUE TITLE
Decidir a estrutura do relatório // Decide report structure

### ISSUE THREAD

**Issue by bcbernardo** [okfn-brasil/censo-querido-diario#30]
## Em português

_For english, see [below](#in-english)._

Abrindo esta Issue para discutirmos a estrutura geral do relatório da primeira parte do Censo do Querido Diário (cidades acima de 100 mil habitantes).

Se utilizarmos a [ferramenta de livros do HackMD](https://hackmd.io/c/tutorials/%2Fs%2Fhow-to-create-book) (ver discussão em #29 ), há dois níveis de organização:

- **Títulos de conteúdo**: sem conteúdo; servem apenas para separar as seções.
- _Capítulos_: cada capítulo é uma "nota", isto é, um arquivo markdown independente, subdividido em quantas seções forem necessárias.

Tentando elaborar um pouco as [propostas](https://docs.google.com/document/d/1i8oJEsC5wfE7vfXzR6vOTC4G2apQMVNlAiHO5lZDn4g "Anotações das reuniões do Querido Diário") que surgiram nas reuniões do Censo até agora, pensei no seguinte rascunho de proposta (_os títulos das seções e capítulos são meramente ilustrativos_):

- _Sumário executivo_. **Nota**: pode incluir "folha de fatos" para download ([exemplo](https://portal.tcu.gov.br/lumis/portal/file/fileDownload.jsp?fileId=8A81881F6CCB7DF3016CDDFF34DD0583 "Ficha-síntese - Auditoria Operacional sobre Obras Paralisadas - TCU")) 
- **Introdução**
  - _Panorama das publicações oficiais no Brasil_
  - _O projeto Querido Diário_
  - _O Censo_
- **Métodos**
  - _Definições_: publicação oficial; ato oficial; portal de publicações oficiais; Formato aberto; (...?). **Nota**: aqui poderiam entrar também conceitos específicos de cada uma das análises. Outra solução é separar os conceitos nas seções em que são usados.
  - _Recorte administrativo, populacional e temporal_: por que municípios e Poder Executivo; início sem recorte populacional e decisão de restringir a 100k; possibilidade de inserir fontes secundárias, para diários antigos; no aspecto populacional, pode incluir análise da representatividade do recorte por regiões brasileiras e fração da população total coberta
  - _Divulgação e engajamento_: formulário de manifestação de interesse, seleção dos grupos de coleta, análise e coordenação, comunicação por Discord e reuniões semanais, campanha oficial da OK, corrente das pessoas embaixadoras.
  - _Coleta_: quem fez a coleta (aberta), link pro FAQ, datas de início, disponibilização da UI e fim dos municípios 100k. **Nota**: pode incluir os pedidos de acesso à informação aos Tribunais de Contas.
  - _Validação_: quem fez as validações, o que olharam, critérios importantes (por exemplo, para considerar um "não existe" diário oficial online), datas de início e fim das validações (apenas municípios 100k)
  - _Análise_: duração das análises, chamados para as pessoas contribuírem com a escrita ou com a exploração de dados, ferramentas de colaboração, (...?).
  - _Política de correção_ como e por quanto tempo receberemos solicitações de revisão dos resultados
- **Resultados: disponibilidade**
  - _Disponibilidade por perfil de município e região geográfica_
  - _Acervo histórico disponível nos portais_
  - _Tempo no ar dos portais_
- **Resultados: usabilidade, acessibilidade e qualidade** 
  - _Avaliação da facilidade de se chegar ao portal_. **Nota**: pode incluir SEO e link no portal da Prefeitura.
  - _Avaliação da acessibilidade dos portais e dos diários_. **Nota**: pode incluir a questão do Captcha, com destaque.
  - _Avaliação da interface dos portais_
  - _Avaliação dos formatos utilizados para publicação dos diários_
- **Resultados: aspectos institucionais**
  - _Quem realiza os serviços de publicação oficial_
  - _Municípios com mais de uma publicação_
- **Principais achados e recomendações**
  - (...)?
- **Quem é quem** 
  - _Sobre a Open Knowledge Brasil_
  - _Sobre o programa Embaixadoras de Tecnologia Cívica_
  - _Quem contribuiu_
- **Contato e como contribuir**
  - _Como relatar um erro ou propor uma melhoria sobre o Censo_
  - _Como utilizar os dados do Censo_
  - _Como contribuir com o Querido Diário_

Comentários?

## In english

_The following translation is machine generated. I might eventually 'humanize' it, if I have the time to do so._

Opening this Issue to discuss the general structure of the report of the first part of the Dear Daily Census (cities above 100 thousand inhabitants).

If we use the [HackMD book tool] (https://hackmd.io/c/tutorials/%2Fs%2Fhow-to-create-book) (see discussion in # 29), there are two levels of organization:

- **Content titles**: no content; they only serve to separate the sections.
- _Chapter_: each chapter is a "note", that is, an independent markdown file, subdivided into as many sections as necessary.

Trying to elaborate a little on the [proposals](https://docs.google.com/document/d/1i8oJEsC5wfE7vfXzR6vOTC4G2apQMVNlAiHO5lZDn4g "Annotations for the Querido Diário meetings") that have emerged at Census meetings so far, I thought of the following draft proposal (_the titles of the sections and chapters are merely illustrative_):

- _Executive summary_. **Note**: may include "fact sheet" for download ([example] (https://portal.tcu.gov.br/lumis/portal/file/fileDownload.jsp?fileId=8A81881F6CCB7DF3016CDDFF34DD0583 "Summary sheet - Operational Audit on Paralyzed Works - TCU "))
- **Introduction**
  - _Panorama of official publications in Brazil_
  - _The Querido Diário project_
  - _The Census_
- **Methods**
  - _Definitions_: official publication; official act; official publications portal; Open format; (...?). **Note**: here you could also enter specific concepts for each analysis. Another solution is to separate the concepts into the sections in which they are used.
  - _Administrative, population and temporal cut_: why municipalities and the Executive Branch; start without population cut and decision to restrict to 100k; possibility to insert secondary sources, for old diaries; in the population aspect, it can include analysis of the representativeness of the clipping by Brazilian regions and fraction of the total population covered
  - _Disclosure and engagement_: form of expression of interest, selection of collection groups, analysis and coordination, communication by Discord and weekly meetings, official OK campaign, chain of ambassadors.
  - _Coleta_: who made the collection (open), link to the FAQ, start dates, availability of the UI and end of the 100k municipalities. *Note*: can include requests for access to information from the Courts of Accounts.
  - _Validation_: who did the validations, what they looked at, important criteria (for example, to consider a "does not exist" official online diary), start and end dates of validations (only 100k municipalities)
  - _Analysis_: duration of analyzes, calls for people to contribute to writing or data exploration, collaboration tools, (...?).
  - _Correction policy_ how and for how long we will receive requests to review results
- **Results: availability**
  - _Availability by profile of municipality and geographic region_
  - _Historical collection available on portals_
  - _Time in the air of portals_
- **Results: usability, accessibility and quality**
  - _Evaluation of the ease of reaching the portal_. **Note**: may include SEO and link on the City Hall portal.
  - _Assessment of accessibility of portals and diaries_. **Note**: can include the Captcha question, with emphasis.
  - _Assessment of the portals interface_
  - _Assessment of formats used for publication of diaries_
- **Results: institutional aspects**
  - _Who carries out the official publication services_
  - _Municipalities with more than one publication_
- **Main findings and recommendations**
  - (...)?
- **Who is who**
  - _About Open Knowledge Brasil_
  - _About the Civic Technology Ambassadors program_
  - _Who contributed_
- **Contact and how to contribute**
  - _How to report an error or propose an improvement on the Census_
  - _How to use Census data_
  - _How to contribute to Querido Diário_

Comments?

**Comment by sergiomario** [comment]
## Em português
Excelente @bcbernardo. Obrigado por ter compilado esse texto.

Eu estou pensando se não podemos ter um capítulo que trate de padrões. Exemplo:
- **Resultados: Padrões**
    - Formato dos arquivos.
    - Se são arquivos únicos ou separados por atos.
    - Se possuem textos em imagens ou outras mídias.

O que acha?

## In english

Excellent @bcbernardo. Thank you for compiling this text.

We could have a chapter on standards. Example:
- **Results: Standards**
     - File format.
     - Single files or separated by acts.
     - If they have text in images or other media.

What do you think?
